version: "3.7"
services:
  mysql-exporter:
    container_name: mysql-exporter
    image: prom/mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=root:hello123@(onestep-db:3306)/
    ports:
      - "9104:9104"
    networks:
      - backend

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.0.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/etc/prometheus"
    ports:
      - 9090:9090
    networks:
      - backend
    depends_on:
      - mysql-exporter

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - prometheus

networks:
  backend:
    external: true
