version: "3.7"
services:
  exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - backend
  prom:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/etc/prometheus"
    ports:
      - 9090:9090
    networks:
      - backend
    depends_on:
      - exporter
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - prom

networks:
  backend:
    external: true
