{
 "title": "Nginx",
 "description": "Dashboard for nginx-prometheus-exporter https://github.com/nginxinc/nginx-prometheus-exporter",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Waiting connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Reading connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_reading{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Writing connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_writing{instance=~\"$instance.*\"}"
    }
   ]
  }
 ]
}