apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Prometheus-PI
    type: prometheus
    access: proxy
    url: http://pi:9090

  - name: LocalMysql
    type: mysql
    url: onestep-db:3306
    database: chen
    user: root
    secureJsonData:
      password: hello123
